### ISSUE TITLE
Trouble converting to YUV 10-bit BT.709

### ISSUE THREAD

**Issue by rafael2k** [fraunhoferhhi/vvenc#103]
I'm trying to feed vvencpp directly with yuv 10 bit. But I'm getting a bit darker images when I input 10 bit samples. Certainly is a ffmpeg color conversion mishap. When converting to yuv 4:2:0 10-bit, should I use "limited" yuv range in the BT.709, right?

I tried many ffmpeg conversion command lines, but I never get it right. Inputting 8-bit to vvenc I get the colors as expected, all good. Any recommendations on how to convert RGB to YUV 10-bit?

**Comment by rafael2k** [comment]
I tried many combinations of (where input file is a jpg):
ffmpeg  -y -i "${input_file}" -color_range 2 -vf scale=in_range=full:out_range=full:out_color_matrix=bt709,format=yuv420p10le -f rawvideo ${TEMPFILEYUV}
and for converting back to 8-bits in the other end, just
ffmpeg -pix_fmt yuv420p10le -s ${resolution} -y -i ${TEMPFILEYUV} -pix_fmt yuv420p ${TEMPFILEYUV2}
and then encoding to jpg with imagemagic / mozjpeg.

**Comment by ValZapod** [comment]
> -i "${input_file}" -color_range 2

This does not make any sense, old jpeg (vs JPEG 2000) is always full range and BT.601 YCbCr matrix, so not needed.

> -vf scale=in_range=full:out_range=full

Why out_range=full? Where are you tagging range? 

>full:out_color_matrix=bt709

Where are you tagging this matrix??

I cannot see primaries and transfer tagging either. sRGB it should be since untagged jpeg is sRGB.

**Comment by rafael2k** [comment]
Right. I should set the correct color primaries and transfer curve, right?
Do you have a sample line which sets the transfer curve and primaries for me to play a bit?

I kind of settled down a bit when using a 8-bit only pipeline worked out of the box for jpg / png encoding.

**Comment by ValZapod** [comment]
> Do you have a sample line which sets the transfer curve and primaries for me to play a bit?

You cannot set this on .yuv files! They only have video data uncompressed. You need to set this by hand in your second command. But really sRGB (transfer sRGB + primaries bt.709, NO MATRIX) is the default so you do need to care in SDR mode at least.

So, for example with full range BT.709 YCbCr:

>ffplay -i file.yuv -vf scale=in_color_matrix=bt709:in_color_range=full,format=gbrp

Same about ffmpeg, but ",format=gbrp" is not needed because of a bug here: https://trac.ffmpeg.org/ticket/8862

Please understand that 10 bit gbrp will not show correctly on SDR 10  or 12 bit screen, only Photoshop works correctly in 10 bit OpenGL and now mpv...

**Comment by ValZapod** [comment]
Also. You jpeg file is 4:2:0 or RGB or CMYK?? Does it have a ICC profile or tagged as sRGB in exif? CMYK is not really supported in FFmpeg (in particular ICC of CMYK do not work but also the limiting of sRGB vs CMYK does not happen). In case of 4:2:0 JPEG the chroma sample location is always center, while with SDR video you should use left. So the change of chroma sample location is needed.

**Comment by adamjw24** [comment]
Can this issue be closed?

**Comment by rafael2k** [comment]
Yes, sure. Can close. I will stick with the "8 bit only" solution, until I have time to dive in all corner cases of converting any image source to VVC and then converting it back to original format.
