### ISSUE TITLE
--qpa 1 cause blurriness, distortion in motion

### ISSUE THREAD

**Issue by ZenKiyoshi** [fraunhoferhhi/vvenc#132]
Windows, latest git master

my command
`ffmpeg -i "Original_Video.mkv" -pix_fmt yuv420p10le -f yuv4mpegpipe -strict -1 - | vvencapp -i - --y4m --preset fast -c yuv420_10 -q 18 --qpa 0 -o "VVenC_fast_qpa0_q18.266"`
`ffmpeg -i "Original_Video.mkv" -pix_fmt yuv420p10le -f yuv4mpegpipe -strict -1 - | vvencapp -i - --y4m --preset fast -c yuv420_10 -q 23 --qpa 1 -o "VVenC_fast_qpa1_q23.266"`
the different -q for matching file size.

When enable qpa, it cause distortion and blurriness in motion.
disble qpa look better

preset fast
https://slow.pics/c/qnfnw1YW
https://slow.pics/c/jirH5eKe
https://slow.pics/c/lGDzjSmT

preset medium
https://slow.pics/c/Ku5JsFkC
https://slow.pics/c/3l1Lk5Jp
https://slow.pics/c/ODHiBWMN

Origin and encoded video: https://drive.google.com/drive/folders/1fXGA6UAhLBGvqDTgEDric_IUh6tOcEq3?usp=sharing

**Comment by adamjw24** [comment]
Did you view the video as a video? Are the artifacts still disturbing?

That's the point of the QPA, to much the bits from dynamic to static areas. It tries to adhere to the human visual system (HVS), which is more sensitive to details in static than dynamic areas. Viewing static frames of a video is not a good test for quality assessment.

What is the bitrate and resolution? Since you are encoding artificial content (Anime would count as such), I assume the bitrate is still really low at the used quantization values.

**Comment by ZenKiyoshi** [comment]
res: 1920x1080
bitrate:
x265: 1760 kb/s
VVenC medium are same around
VVenC fast little bit higher bitrate
I try adjusting VVenC -q parameter to achive same filesize

> Did you view the video as a video? Are the artifacts still disturbing?

Yes I view video normally and of cource I am hard to see the artifacts.

> That's the point of the QPA, to much the bits from dynamic to static areas.

I see QPA act like aq-mode in x264/x265, but it tend to take to much bitrate and make distortion.

**Comment by adamjw24** [comment]
I see.

QPA is kind of similar to aq-mode, except it is more complex. It is based the XPSNR measure, which is an eXtended version of WPSNR measure, both developed by my colleague C. R. Helmrich (see http://www.ecodis.de/xpsnr.htm).

The extension of the of XPSNR over WPSNR is the inclusion of temporal activity measure (in addition to the spacial activity used in WPSNR). So the QPA based on XPSNR would adapt the local QP based on both the spacial as well as temporal complexity of a scene (i.e. motion). The aq-mode, as far as I understand only depends on the spacial complexity. That's why you see the difference.

**Comment by adamjw24** [comment]
Did you have a look at other parts of the picture? The QPA, while introducing some blurring to motion, should make static parts by far better (i.e. remove banding and blocking that you can actually see in a video).

**Comment by ZenKiyoshi** [comment]
Yes, any parts don't move look better.

In this frame https://slow.pics/c/ZG4IcvMp
only some blurry in motion at the bottom right corner.

And question: Could the QPA effect can be adjusted? 
x265 aq-mode has a related paremeter call aq-strength to adjust it's strength. It's nice to see VVenC has one.

**Comment by adamjw24** [comment]
VVenC should look better than x265 at the same rate either way. I hope it still does look at least as good as x265 at way lower rate (say around 1mbps).

Just as a side note, QPA can "redistribute" the bitrate between the frames in constant QP mode, thats why you see bitrate differences for QPA=0/1. When using rate control, local QP adaptations would average out to 0, meaning the bitrate of the frames is unchanged. So with rate control, QPA would not affect the resulting rate so much (as you would expect with rate control either way).

You cannot adjust QPA strenght so far. We can consider it as a future feature, but it would not happen soon (just because for now there are other features in the pipeline).

**Comment by adamjw24** [comment]
So we looked at it, and it seems there is no way to change the weighting in a way that would make it look better in motion scenes than just disabling QPA (which in turn makes static scenes worse, and decreases the overall quality impression). QPA on-off seems like a good granularity of choice.

If you want to play around feel free to see how the `2.0`-weighting in https://github.com/fraunhoferhhi/vvenc/blob/69469d7ac5de882d9f5e12b24ee87f376df20262/source/Lib/EncoderLib/BitAllocation.cpp#L188 and https://github.com/fraunhoferhhi/vvenc/blob/69469d7ac5de882d9f5e12b24ee87f376df20262/source/Lib/EncoderLib/BitAllocation.cpp#L228 affects your scenes. This would require code-changes and recompiling, though.

**Comment by e8m-8** [comment]
> So we looked at it, and it seems there is no way to change the weighting in a way that would make it look better in motion scenes than just disabling QPA (which in turn makes static scenes worse, and decreases the overall quality impression). QPA on-off seems like a good granularity of choice.
> 
> If you want to play around feel free to see how the `2.0`-weighting in
> 
> https://github.com/fraunhoferhhi/vvenc/blob/69469d7ac5de882d9f5e12b24ee87f376df20262/source/Lib/EncoderLib/BitAllocation.cpp#L188
> 
> and
> https://github.com/fraunhoferhhi/vvenc/blob/69469d7ac5de882d9f5e12b24ee87f376df20262/source/Lib/EncoderLib/BitAllocation.cpp#L228
> 
> affects your scenes. This would require code-changes and recompiling, though.

QPA has good visual quality at low QP values (15 to 23). XPSNR is very efficient.
However, at high QP values (30 to 40), moving objects are visually too blurry and sometimes blocky.
I changed the values of saAct and taAct, e.g. reducing the QP value to 5 for motion images and 7 for still images. Videos with multi-motion scenes have a bitrate approximating QP +6.

```
/source/Lib/EncoderLib/BitAllocation.cpp
va.hpSpatAct = double (8.0 * saAct) / double ((width - 4) * (height - 4));
va.hpSpatAct = double (8.0 * saAct) / double ((width - 2) * (height - 2));
va.hpTempAct = double (1.5 * taAct) / double ((width - 4) * (height - 4));
va.hpTempAct = double (1.5 * taAct) / double ((width - 2) * (height - 2));
```

This change seems to affect the CU of the still image, and even if the SSIM values are the same, it gets worse in some small areas occasionally.
If the QP could be reduced for complex images only, it might actually give better visual performance.

![S8T1 5 VS S1T1](https://github.com/user-attachments/assets/c5ca6241-2dd9-4613-8ce4-af7b6bb1c04a)

**Comment by e8m-8** [comment]
I used a YUV Music Video (from Prores 422) with noise reduction in 1920x1080 25fps YUV420P10LE format.
Here are my arguments:
`vvencFFapp -i -  --y4m --Preset fast --Level 5.1 --FrameRate 25 --QP 28 --PerceptQPA 1 --IntraPeriod 128 --GOPSize 32 --MinIntraDistance 1 -b SC8TC1.5-QPA-28.266`
