### ISSUE TITLE
how to compile vvenc and its decoder (vvdec) with ffmpeg?

### ISSUE THREAD

**Issue by benpar2** [fraunhoferhhi/vvenc#153]
This is not an issue, just it is a question. How can I compile vvenc and vvdec with ffmpeg?

**Comment by 1480c1** [comment]
Here's an answer https://github.com/fraunhoferhhi/vvenc/issues/140#issuecomment-1046273595

**Comment by Jamaika1** [comment]
Now it's a mess. Open VVC is still being written. Does not decode the latest VVC.
The latest EVCs are elsewhere and linked to OpenVVC.
https://github.com/OpenVVC/FFmpeg
https://github.com/mpeg5/ffevc
Anyone trying to merge? Yes but it's a long way.
https://github.com/eocene317/LTM-master

**Comment by adamjw24** [comment]
> Now it's a mess. Open VVC is still being written. Does not decode the latest VVC. The latest EVCs are elsewhere and linked to OpenVVC. https://github.com/OpenVVC/FFmpeg https://github.com/mpeg5/ffevc Anyone trying to merge? Yes but it's a long way. https://github.com/eocene317/LTM-master

What is this even? How is evc and lcevc stuff even related to the problem?

**Comment by adamjw24** [comment]
VVenC cannot be compiled together with FFmpeg. Noone has done an integration yet, and for us the licese is too restrictive to do that.

VVdeC is supported in a few FFmpeg forks, and @1480c1 pointed you to the correct resources. Possibly you could use https://github.com/lehmann-c/FFmpeg instead of tbiat/FFmpeg as the fork, as it contains a few bugfixes.
