### ISSUE TITLE
command line of multi-thread testing.

### ISSUE THREAD

**Issue by liuyin-98** [fraunhoferhhi/vvenc#168]
Hi!

I have conducted some experiments on multi-thread and found that the encoding time of using single thread is about as 10 times as that of using 32 threads on UHD sequences under RA_faster configuration. It is amazing but still less than 15 times claimed in the whitepaper. I wonder if my test condition is different from yours. 
Could you please tell me your command line for testing. 

This is the command line I use. 
_vvencFFapp.exe -c randomaccess_faster.cfg -c Sequences\Tango2.cfg  -t 32 --QP=37         1>ClassA1_t32\Tango2.37.log_ 

The CPU I use is Xeon Gold 6154 with 36 threads.

Thanks in advance,
Yin.

**Comment by adamjw24** [comment]
Dear Yin,

nice to see you experimenting with vvenc. The whitepaper is outdated, have a look at the Wiki for the most up-to-date information.

Now about the multi-threading, there are 2 things to consider.

The presented results show the runtime when the CPU is fully utilized. So its a single-threaded runtime, when 16 concurrent instances are running, vs a single 16-thread instance. If you run a single single-threaded instance on Intel CPUs it tends to turbo-boost and generally increase CPU-freuquency. So 

As stated in the Wiki, the last results are from the version 0.3. Back than preset faster was much slower than today, frankly making parallelization easier (its easier to parallelize long tasks). Since than we increased single-threaded efficiency by a lot, but this impairs MT-performance a bit.

We are working on generating new set of results (for a paper), and when we have the numbers we'll update the figures.

Back than, I used the following script to generate the results:
```sh
for t in 16x 16 12 8 6 4 2 0; do

  if [ "$t" = "16x" ]; then
    T=16
    OPTS="--threads ${T} --WaveFrontSynchro=1"
  elif [ "$t" = "0" ]; then
    T=1
    OPTS="--threads 0"
  else
    T=$t
    OPTS="--threads ${T}"
  fi
  
  PARALLEL=$(expr $CPU / $T)
  
  if [ $PARALLEL -gt $MAXJOBS ]; then
    PARALLEL=$MAXJOBS
  fi
  
  echo "Running ${T}-threaded encodings as ${PARALLEL} jobs"
  
  for p in $PRESETS; do
    for QP in $QPS; do
      for c in $CFGSA $CFGSB; do
        SEQ=$(basename $c .cfg)
        TMPRES=${TMP}/${SEQ}_QP${QP}_${p}_t${t}.txt
        RES=${OUT}/${SEQ}_QP${QP}_${p}_t${t}.txt
        if [ ! -f "${RES}" ]; then
          echo "${ENC} --QP=${QP} --preset ${p} -c ${c} ${OPTS} -b /dev/null -o /dev/null > ${TMPRES}; cp ${TMPRES} ${RES}"
        fi
      done
    done
  done | parallel -j $PARALLEL
  #done >> jobs.txt
done

```

**Comment by liuyin-98** [comment]
Thanks a lot for your immediate response!

I still confuse about the "16 single-thread instances vs. single 16-thread instance". Base on the script you present, do you mean I have to run more than 1 single-thread instance when testing single-thread perfomance to eliminate the acceleration from Intel CPU's single-thread optimization?

And the experiments I have done is on Windows10 platform, does it matter?

**Comment by adamjw24** [comment]
> I still confuse about the "16 single-thread instances vs. single 16-thread instance". Base on the script you present, do you mean I have to run more than 1 single-thread instance when testing single-thread perfomance to eliminate the acceleration from Intel CPU's single-thread optimization?

Exactly!

> And the experiments I have done is on Windows10 platform, does it matter?

I hope this would not matter, didn't make the test though.

**Comment by liuyin-98** [comment]
Got it! Thanks a lot!

**Comment by adamjw24** [comment]
Update the data with 1.6.0 measurements
