### ISSUE TITLE
CMake presumes x86 SIMD and ignores ARM at all

### ISSUE THREAD

**Issue by zhguyu** [fraunhoferhhi/vvenc#175]
To build the project on an ARM-based environment other an Apple (e.g. Raspberry Pi) requires manually editing CMakeLists.txt at the moment because it doesn't actually detect what platform you have and presumes x86.

**Comment by adamjw24** [comment]
VVenC is for now an encoder supporting exclusively the x86 platform. Since Rosetta2 is such an amazing emulation environment, we support compilation under Mac OS X. For that reason there is no need to support any other build targets.

We are planning to add ARM support with SIMD everywhere, analogue to VVdeC, sometime in Fall 2022. After this feature has been implemented VVenC will properly build as an ARM binary on ARM targets.

**Comment by zhguyu** [comment]
Thanks for the explanation.

Sure there is a roadmap, but still I can’t see why building on generic ARM targets has to be intentionally _blocked_. After all, it still works without SIMD intrinsics.

**Comment by zhguyu** [comment]
I see. Anyways, after playing around with vvenc I believe it’s already an excellent encoder at this point and thanks for the hard work.

**Comment by adamjw24** [comment]
Thanks.

As mentioned, you can expect ARM support, with proper testing as a supported platform, after the summer.
