### ISSUE TITLE
Windows .rc file also works in MinGW environment

### ISSUE THREAD

**Issue by zhguyu** [fraunhoferhhi/vvenc#179]
https://github.com/fraunhoferhhi/vvenc/blob/774eb14ff01902bd25053029404c46ff75c094e8/source/App/vvencapp/CMakeLists.txt#L17-L20

**Comment by zhguyu** [comment]
And there's actually a pretty solid reason for using MinGW, either Clang or GCC, over MSVC as the executables produced by the former compilers yields around ~8.5% speedup:

MSVC flags: /O2 /Ob3 /DNDEBUG /GL

Clang/GCC flags: -O3 -DNDEBUG -ffast-math -flto
Clang/GCC linker flags: -s -static

vvencapp flags: --qp 24 --preset fast -v info

**Clang**
```
vvencapp: Fraunhofer VVC Encoder ver. 1.5.0-rc1 [Windows][clang 14.0.4][64 bit][SIMD=AVX2]
Total Time: 671.069 sec. Fps(avg): 2.980 encoded Frames 2000
```
**GCC**
```
vvencapp: Fraunhofer VVC Encoder ver. 1.5.0-rc1 [Windows][GCC 12.1.0][64 bit][SIMD=AVX2]
Total Time: 665.851 sec. Fps(avg): 3.004 encoded Frames 2000
```
**MSVC**
```
vvencapp: Fraunhofer VVC Encoder ver. 1.5.0-rc1 [Windows][VS 1932][64 bit][SIMD=AVX2]
Total Time: 729.166 sec. Fps(avg): 2.743 encoded Frames 2000
```

**PSNR comparison**
```
        Total Frames |   Bitrate     Y-PSNR    U-PSNR    V-PSNR    YUV-PSNR
             2000    a    5515.9811   50.0344   51.5110   48.7743   49.4824
             2000    a    5516.0845   50.0345   51.5110   48.7744   49.4825
             2000    a    5516.6143   50.0349   51.5107   48.7737   49.4826
```

**Comment by adamjw24** [comment]
Interesting. We'll have a look. Thanks for pointing that out.

Always makes me shiver when different runs produce different results for the same opts, but I guess that's normal with floating point calculations.

**Comment by adamjw24** [comment]
So we talked it over with some build experts.

How exactly do you build it? We can already build under Windows using MSYS (https://github.com/m-ab-s/media-autobuild_suite) and it seems to mostly work.

Why would we need an RC-file at all? It only sets some metadata. In the end, vvencapp is just a cmd-line command.

Also, the way to go to build a GCC/Clang version for Windows is through cross-compilation with Linux, in which case we would not be able to include the RC-file either way, no?

Could you elaborate? And since you have a version that somehow works, feel free to make it to a pull request.

**Comment by zhguyu** [comment]
> Also, the way to go to build a GCC/Clang version for Windows is through cross-compilation with Linux, in which case we would not be able to include the RC-file either way, no? Building on Windows in MSYS/Cygwin etc is only a workaround.

You're right about the MSYS thing. In most cases when we refer to MSYS or MinGW we are actually talking about MSYS2 which is a successor (in my mind) to MSYS, Cygwin or MinGW. It comes with the most up-to-date toolchains and libraries.

I wouldn't consider using MSYS2 as a workaround over cross-compilation from Linux. As I said, MSYS2 comes with the most up-to-date toolchains, even newer than many that is offered in certain Linux distros, Debian for example. Also, the compiled binaries can work natively in Windows shell so long as it is strictly statically linked, and that's exactly why I included my compiler flags in the previous post. Most importantly, as I showed, the binaries compiled with Clang and GCC have a decent speedup over MSVC, and that should be a good enough motivation for using MSYS2. Finally, using CMake in MSYS2 is also pretty straightforward and, in my opinion, easier than the CMake + MSBuild combination.

The RC file thing is only a minor note that I want to mention because, hey, it's only one line of code to change. Building with MSYS2 enables you to attach a Windows-style RC file to the binary just like what you do using Visual Studio. That's enabled by a package called `windres`.

**Comment by adamjw24** [comment]
Apparently some colleagues have been experimenting with that and there is a long experience with RC fiels beeing incompatible between MSVC and MinGW/... environment. We would probably in that case need to maintain multiple version of the RC file. I am not an expert in this myself, so I have to trust the advice. I think for what an RC file has to offer, it might not be worth the effort.

About the compilation itself, everyone is free to use the build system of their choice, and we try to make it all work. I don't think we should disable or deprecate MSVC at this point, also because its still the best for development. But I'll keep that in mind if someone wants an advice on e.g. deploying on Windows.
