### ISSUE TITLE
is that a bug?

### ISSUE THREAD

**Issue by pigpeppa** [fraunhoferhhi/vvenc#18]
int remRegBins = (uiWidth * uiHeight * ctxBinSampleRatio) >> 4; in file QuantRDOQ.cpp

For my understanding, it should be int remRegBins = (tu.getTbAreaAfterCoefZeroOut(compID) * ctxBinSampleRatio) >> 4;

**Comment by adamjw24** [comment]
Its a minor bug. QuantRDOQ.cpp is never used. It is the RDOQ ported from VTM when initially setting up the code, with have it for compatibility reasons only. In VVenC either DQ is used ("medium" through "slower") or RDOQ2 otherwise (our own integer-based RDOQ implementation). Also, its only a rate estimation bug, so it still produces valid results, only suboptimal. When we fixed this for RDOQ2 a while back I remember the impact being very minor. Still, fell free to fix that. Otherwise we'll fix in the upcoming relaese.
