### ISSUE TITLE
Output yuv file size increased

### ISSUE THREAD

**Issue by john17978** [fraunhoferhhi/vvenc#26]
Hello

 I encode the YUV file (926 MB) with this command

`vvencapp.exe -i input.yuv -s 1280x720 -r 30 -f 670 --preset medium -o output.266`

and decode it with this command

`vvdecapp.exe -b output.266 -f 670 -o back.yuv`

The problem is when i decode the file,  back.yuv file is 2x larger than input.yuv

How can I fix this problem?

Regards.

**Comment by adamjw24** [comment]
The default for vvencapp is to encode with 10bit internal bit depth (its independent of the input bitdepth). This causes the decoder to produce a yuv420p10le rather than yuv420p as it would for 8-bit internal bit depth bitstream.

See this issue for vvdec on explanation: https://github.com/fraunhoferhhi/vvdec/issues/4

You can use --interal-bitdepth parameter to control the encoder behavior (its listed with the --fullhelp). We want to implement 8-bit output for 10-bit internal bit-depth for vvdec, but the is fixed plan for this feature yet.

Hope this help.s

**Comment by john17978** [comment]
Thank you for quick response.  I will look into it.

**Comment by gopi77** [comment]
The command
--internal-bitdepth=8
