### ISSUE TITLE
Dose vvencapp support arbitrary GOP size?

### ISSUE THREAD

**Issue by UpTownCat** [fraunhoferhhi/vvenc#28]
I use vvencapp to encode video, -g option only accepts [16, 32] but I want to set 24 gop size, Is there a way to do this?

**Comment by adamjw24** [comment]
Why would you want to set GOP size to 24?

If the GOP size is not a power of two the hierarchical structure will be somehow unbalanced - i.e. probably like a mix of interleaving gop-16 and gop-8 structures, meaning it would also produce suboptimal results.

Since we don't want to decide how it should be unbalanced nor have an algorithm that can decide the optimum between gop16-gop8, gop8-gop16 and gop8-gop8-gop8 or even more fine-granular imbalance (i.e. on higher temporal depths), there is no setting to do that.

To run a GOP24 encoding you'd need to define your own GOP structure in the expert app (defining reference pictures lists, QP offsets and all that stuff for each frame in the GOP), which is indeed an expert setting.

**Comment by UpTownCat** [comment]
Thanks for quick response.

I want to encode videos for streaming, most input videos are 24 or 25 fps, so setting GOP to 1 seconds or 3 seconds is helpful to generate same duration dash m4s segments. 

If I can't use the standard encoder to do this, I may need to change input videos to 32fps.

**Comment by adamjw24** [comment]
So in your case you want an intra-period (IP) of 24. I guess the best way to do this would be to have a GOP of 24, but the problem applies. The easiest hack around this would be to have a GOP8 structure, because for now intra period has to be a multiple of GOP size. I think older version of HM have a GOP8 configured so you could adapt their configuration (it should use similar semantics to the expert encoder parametrization). Doing that will cost a lot of efficiency, though. So for proper application right now you'd need to adapt the segment size to 1.3 seconds (32 frames), or a multiple of that.

I guess we can evaluate it internally if the the intra-period necessarily has to be a multiple of the GOP size, in which case e.g. a GOP32 could be just cut short (frame 24 would be an I-frame instead of temporal layer 2 B-frame and the frames 25-31 in the GOP would be skipped, as they would be transmitted in the next IP, so also next GOP). But since it requires some experiments and might produce too much overhead for us to officially support it, I would not count on seeing this feature soon, if at all.

**Comment by UpTownCat** [comment]
Got it, thanks for help.
