### ISSUE TITLE
The roadmap about lowdelay configuration

### ISSUE THREAD

**Issue by spartazhc** [fraunhoferhhi/vvenc#35]
Currently the lowdelay related configurations are placed in `cfg/experimental/`, in `vvencCfg.cpp` there are `confirmParameter` against lowdelay configuration: 
https://github.com/fraunhoferhhi/vvenc/blob/3c039585deea24f3d57558ac4fbd0590d629b185/source/Lib/vvenc/vvencCfg.cpp#L113
https://github.com/fraunhoferhhi/vvenc/blob/3c039585deea24f3d57558ac4fbd0590d629b185/source/Lib/vvenc/vvencCfg.cpp#L120
https://github.com/fraunhoferhhi/vvenc/blob/3c039585deea24f3d57558ac4fbd0590d629b185/source/Lib/vvenc/vvencCfg.cpp#L1538-L1539

I would like to ask when will lowdelay configuration be avaliable? Thanks!

**Comment by adamjw24** [comment]
So we are not planning to officially support low delay in the near future, that's why those configs are experimental. So the multi-threading will work worse, the results might not be as good and the configurations possibly not pareto-optimal.

With the #36 at least the lib should allow you to configure a low-delay temporal structure.

**Comment by spartazhc** [comment]
Understand that, thanks a lot!
