### ISSUE TITLE
FFmpeg Integration

### ISSUE THREAD

**Issue by F1FAQ** [fraunhoferhhi/vvenc#361]
I need vvenc and vvdec embedded in ffmpeg. I found on the wiki the FFMPEG integration (under Windows) via media-autobuild_suite, but the compilation failed. 
Failure message is : "Patch could not be applied with git am. Continuing without patching" 
The media-autobuild_suite website confirmed that the procedure to patch ffmpeg with vvdec and vvenc should be updated (rebase the ptach)
Is this something that can be done ?
Thank you

**Comment by classicdoomenjoyer** [comment]
I am getting that exact same problem.

I just can't get VVC encoders/decoders in FFMPEG.

**Comment by adamjw24** [comment]
Which version of FFmpeg are you applying the patches to? As you can see in the Wiki, its best applied to n6.1. When you are using media autobuild suite, I think it always works with the newest versions of all projects. Regretfully, the project doesn't have proper versioning so its up to you to deal with the mess.

Updating the patchset is surely something that can be done. I don't think anyone is working on it tho, since FFmpeg now has its own decoder.

**Comment by birdie-github** [comment]
The wiki page specified the exact ffmpeg version/git revision these patches still apply. They no longer apply because `ffmpeg` has started to support VVC decoding natively but the work isn't completed yet. Once it all settles down I expect these patched to be updated.

In the meantime you can pipe from/to ffmpeg to continue to use it with vvenc/vvdec.

**Comment by adamjw24** [comment]
> In the meantime you can pipe from/to ffmpeg to continue to use it with vvenc/vvdec.

Please do not pipe from vvdec, its not 1990 anymore.

**Comment by F1FAQ** [comment]
Thank you to all who made a comment. I succesfully compiled ffmpeg with vvdec and vvenc by specifying ffmpeg release 6.1.1 in media-autobuild_suite. adamjw24 had the answer !

**Comment by classicdoomenjoyer** [comment]
> Thank you to all who made a comment. I succesfully compiled ffmpeg with vvdec and vvenc by specifying ffmpeg release 6.1.1 in media-autobuild_suite. adamjw24 had the answer !


I followed all the steps given here in the Build section to how to build FFMPEG with VVC support:

https://github.com/fraunhoferhhi/vvenc

But, still, I failed. vvenc and vvdec is still not included in my build ☹️

**Comment by adamjw24** [comment]
For me the issue is closed

**Comment by classicdoomenjoyer** [comment]
> For me the issue is closed

But sir, its not fixed for me yet. Please don't ignore me.

**Comment by classicdoomenjoyer** [comment]
Btw, what's the status on upstreaming the patches to get it in the master branch of FFMPEG ?

**Comment by birdie-github** [comment]
> Btw, what's the status on upstreaming the patches to get it in the master branch of FFMPEG ?

This is done by people not related to this project. Maybe you could ask them directly.
