### ISSUE TITLE
About new multithreading encoder option IFP

### ISSUE THREAD

**Issue by thx4ever** [fraunhoferhhi/vvenc#370]
Hi, im trying to figure out how to encode with IFP on because if use IFP it uses about 17% only of my 18 core cpu
Can u explain what options i need to use and what options i dont need?

Thanks 

Regards

**Comment by adamjw24** [comment]
Hi,

Soo, first of all, what command do you use? Let me know and I’ll try to give you some recommendations on how to optimize that.

Mind that the default number of threads is still 12 for 5K+, 8 for 720p+ and 4 otherwise. You have to enable additional threads to be used, even when IFP is enabled (otherwise you should be seeing a warning).

Further, IFP really works best for the preset faster. For other presets it might be more efficient to just use a faster preset, considering all options allowing more threading cause additional loss (but also IFP is the best option to use there, if your content doesn’t have black margins).

Further, IFP works better for larger videos, so at least 720p is recommended.

Best, Adam

From: thx4ever ***@***.***>
Sent: Thursday, March 28, 2024 11:47 PM
To: fraunhoferhhi/vvenc ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [fraunhoferhhi/vvenc] About new multithreading encoder option IFP (Issue #370)


Hi, im trying to figure out how to encode with IFP on because if use IFP it uses about 17% only of my 18 core cpu
Can u explain what options i need to use and what options i dont need?

Thanks

Regards
