### ISSUE TITLE
Can someone share the gop64.cfg and gop128.cfg? 

### ISSUE THREAD

**Issue by dhwi96** [fraunhoferhhi/vvenc#419]
Is there any experiences with cfg file for the gop 64 and gop 128?
If there someone who has the diverse gop configuration cfgs, could anyone share it with me if possible?

Thank you.

**Comment by adamjw24** [comment]
FYI, in VVenC, a GOP is what a mini GOP is in other encoders. What in other encoders a GOP is, is an intra period in VVenC. You can set the intra period using `--IntraPeriod=64`. An actual minigop of 64 or 128, so as you call GOP64 or GOP128, would not work, since many encoder algorithms assume (mini) GOP size of maximally 32.

Best, Adam
