### ISSUE TITLE
Arm implmentation refers to x86_64 code? 

### ISSUE THREAD

**Issue by BrytonLee** [fraunhoferhhi/vvenc#449]
Hi,

I saw some Arm codes refer to x86_64 code, it is not reasonable.  For example:
https://github.com/fraunhoferhhi/vvenc/blob/3f2dcf49193ac804634ae95adfa6f17236329b86/source/Lib/CommonLib/arm/RdCostARM.h#L54

And there are many operators that are not implement by Arm Neon/SVE instructions, do you have any plan to do that? 

Thanks.

**Comment by K-os** [comment]
Yes, it is perfectly reasonable. SIMD-Everywhere is used to translate the x86 SIMD code to ARM. The CMake step even prints a message that enabling x86 SIMD intrinsics on non-x86 targets is intentional.

Concerning your question about the functions without a specific ARM implementation: the functions with the most performance impact/least benefit from simd-everywhere have been reimplemented using NEON intrinsics first. Further improved implementations have been contributed just recently #425, #431, and #444. Feel free to contribute further optimized implementations.
