### ISSUE TITLE
[Feature request] Y4M support inside of VVenC

### ISSUE THREAD

**Issue by BlueSwordM** [fraunhoferhhi/vvenc#65]
Hello. I've been trying out VVenC recently, and I've noticed that this encoder doesn't support y4m input for some reason.

Are there any plans into bringing y4m support into the encoder? Having to pipe YUV and specifying the data is fine, but it is not optimal and makes the encoding workflow more annoying, even when scripted.

Might as well add in y4m support in VVdec.

**Comment by master-of-zen** [comment]
Yes please

**Comment by master-of-zen** [comment]
Y4M input still would be good

**Comment by master-of-zen** [comment]
Sometimes, when I drink tea I have a thought: "Yeah, y4m support on VVenC would be good... wish that was added"

**Comment by sgmihai** [comment]
This is a corporate codec, not open av1 development, where issue requests are actually analyzed.

**Comment by adamjw24** [comment]
@sgmihai I reported you for harassment.

Just as a reference. Fraunhofer is a "Verein", which means it is a public entity that is forbidden from making profit. All money is invested into ongoing and future operations. For this reason alone VVenC cannot be corporate.

It's easy as a user to only demand stuff. We are a small team fully invested in developing more important features. Everyone is welcome to contributed. But open source does not mean we work for the users.

I'm closing this issue because of the negative energy.

**Comment by adamjw24** [comment]
If Y4M support really is a blocker for anyone, please refer to: https://github.com/fraunhoferhhi/vvenc/discussions/116
