### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by Soaibkhan38** [fraunhoferhhi/vvenc#8]
![image](https://user-images.githubusercontent.com/6275744/99996888-611bc200-2de2-11eb-9c0b-958676f5d051.png)
I built a static release and tried to encode a raw yuv stream. It keeps giving Segmentation fault.
Thanks

**Comment by adamjw24** [comment]
How did you generate the input? What computer (CPU/mem) are you using it on? Which release are you using? Did you try using other presets?

**Comment by Soaibkhan38** [comment]
Input raw was decoded from an H.264 raw that I had. CPU- Intel i5-8250u, Mem- 12gb. Yesterday, I cloned the repo and compiled it on my WSL Ubuntu machine using "make install-release". Same error with --preset medium
![image](https://user-images.githubusercontent.com/6275744/100081625-3dea2480-2e6d-11eb-8415-402e6eeabbc5.png)

**Comment by adamjw24** [comment]
Are you sure your output is 10bit? I'm not sure h264 supports that per default. You need the high-bit-depth profile.
Would you mind sharing the first few frames of the video for me to try to reproduce the exact problem?
Otherwise, do you think it would be possible for you to start the run in gdb (using the relwithdebinfo build) and share the stack trace?

Having said that, I had some problems with the WSL runs that are not reproducible on native architectures. You could try compiling with VS (community edition should alright), VSC should also work.

**Comment by Soaibkhan38** [comment]
I changed the output format to 8bit again and it worked. But I have been using 10bit output for my encodes in H.265. I tried compiling it with Make on windows, kept getting an error that I don't have Visual C++, though I installed it. So, switched to WSL for compiling. This is the source of the H.264 video, which I converted to raw video.
"magnet:?xt=urn:btih:5c20613b84863c88bec82f8b48ff4ccf875cec85&dn=%5bSubsPlease%5d%20Taisou%20Zamurai%20-%2007%20(1080p)%20%5b821FD5CB%5d.mkv&tr=http%3a%2f%2fnyaa.tracker.wf%3a7777%2fannounce&tr=udp%3a%2f%2ftracker.coppersurfer.tk%3a6969%2fannounce&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce&tr=udp%3a%2f%2f9.rarbg.to%3a2710%2fannounce&tr=udp%3a%2f%2f9.rarbg.me%3a2710%2fannounce&tr=udp%3a%2f%2ftracker.leechers-paradise.org%3a6969%2fannounce&tr=udp%3a%2f%2ftracker.internetwarriors.net%3a1337%2fannounce&tr=udp%3a%2f%2ftracker.cyberia.is%3a6969%2fannounce&tr=udp%3a%2f%2fexodus.desync.com%3a6969%2fannounce&tr=udp%3a%2f%2ftracker3.itzmx.com%3a6961%2fannounce&tr=udp%3a%2f%2ftracker.torrent.eu.org%3a451%2fannounce&tr=udp%3a%2f%2ftracker.tiny-vps.com%3a6969%2fannounce&tr=udp%3a%2f%2fretracker.lanta-net.ru%3a2710%2fannounce&tr=http%3a%2f%2fopen.acgnxtracker.com%3a80%2fannounce&tr=wss%3a%2f%2ftracker.openwebtorrent.com"

Sorry for sharing a pirated video.
I can't comprehend the gd part that you have mentioned. I am not familiar with all this development stuff, just wanted some VVC encode testing.
Also, is it possible for it to stop me from using certain commands rather than just break and give a Segmentation fault?
Sorry for the inconvenience, and thanks

**Comment by adamjw24** [comment]
I hope you understand I can't really use the "link" to look into the problem, last but not least because I don't know how it would be accessed. I'd appreciate if you removed it from the comment.

About the VC++ compilation. You need to have all the path variables set. Easiest way is just to start the developer command prompt of your VC installation.

About the 10-bit content, there are different ways to represent. If I encode 8-bit video as yuv420_10, I also get a segmentation fault. So maybe your conversion produced a "packed" format?

Best way to produce 10-bit content compatible with our encoder is using ffmpeg:
ffmepg -i input.mp4/wmv/whatever -s WxH -f rawvideo -pix_fmt yuv420p10le raw_yuv_10bit.yuv

Concerning your last point, this cannot be checked during parameter parsing. You provide "raw" content, so basically to catch this error we would need the encoder to go through your provided input and confirm every sample is within the provided range (0-1023). This would provide very considerable overhead. But we might add a few checks here and there to maybe allow the encoder to fail in a more meaningful way.

**Comment by Soaibkhan38** [comment]
Thanks for the input regarding the generation of a 10bit stream, I'll try and test with it. I will try with VC++ or will cross-compile with MinGW on Linux. Closing this issue here.
