### ISSUE TITLE
Rate control has problems

### ISSUE THREAD

**Issue by rafael2k** [fraunhoferhhi/vvenc#93]
When encoding still images at low bitrate (80kbit per pic, SD resolution) - all good happens if the image has low entropy, and the picture matches the size specified by "-b" (-r 1). If the image is of high entropy, the encoder chooses a very bad qp (49 for eg), and instead of 10 kbytes, the encoded picture is 3 or 4 kbytes (and obviously has an awful quality).

Also I don't really know the correct syntax for "--profile", but I always get an error when I try to use it:
Error parsing option "profile" with argument "main10".
or
Error parsing option "profile" with argument "main10_stillpic"

**Comment by adamjw24** [comment]
The rate control algorithms were not designed for single image coding. The QP adaptation is done on a per-image basis, and not per-CTU, which would be more suited for this use-case.
Did you try the 2-pass rate-control? It has a somehow more stable QP selection model.

Either way, we'll have a look into this.

About the profile issue. Please try with an underscore between main and 10, i.e. "main_10".

**Comment by rafael2k** [comment]
Thanks Adam. Yes, I tried the 2-pass rc - no luck. Is there a way to change this behavior of the qp adaptation?

**Comment by adamjw24** [comment]
No, we removed the old code. It seems there is no quick fix right now. We will include still pic RC into the agenda, but I wouldn't expect results too soon.

For now if you feel like doing a workaround, maybe try doing this in the application level? You could do a few encodings in faster preset to find the QP. Than with the final QP encode in your desired preset (should mostly improve quality, and only reduce the rate slightly). Should not be too much runtime overhead if you work with medium or slow(er) for the final encode.

**Comment by rafael2k** [comment]
For now I'll do this workaround and run the encoder in a iterative way to find the QP which gives me the final size I need. Tks!
Btw, the reference implementation has this RC logic which works better for still pic implemented?

**Comment by adamjw24** [comment]
About the reference SW, I think so, but not sure. Either way, the VTM RC is bad and should not be used, and I think you're still faster overall with rate screening using the faster preset and final encoding in your chosen setting.

The only reason to use VTM right now would be for the full 444 support.

**Comment by rafael2k** [comment]
Thanks Adam. We'll use yours VVC implementation. Still images in 420 looks fine for very low bitrate, no problem. Today I'll commit the iterative bash encoding script implementation here: https://github.com/DigitalHERMES/rhizo-uuardop/blob/master/scripts/compress_image.sh

**Comment by crhelmrich** [comment]
Hi Rafael,

I'm one of the developers of the 2-pass rate control algorithm and currently testing an improvement for still image coding. You wrote that (emphasis mine) "If the image is of high entropy, the encoder chooses a very bad qp (**49 for eg**), and instead of 10 kbytes, the encoded picture is **3 or 4 kbytes** (and obviously has an awful quality)." Would it be possible for you to share that input image so I can evaluate the behavior of my modifications in that particular scenario?

Thanks,

Christian

**Comment by rafael2k** [comment]
Dear Christian, sure.
A 4:2:0 yuv:
http://www.abradig.org.br/vvc/image-840x628.yuv
vvcenc line used:
vvencapp -i image-840x628.yuv --profile main_10_still_picture --qpa 1 -t 2 -r 1 -b 80000 -s 840x628 --preset medium -c yuv420 -o out.vvc

**Comment by crhelmrich** [comment]
Thanks very much! This image is truly an extreme case and very hard to encode with only 80 kbit (10 kbytes). What supports this observation is that, as an example, encoding this image in AVIF format in Gimp 2.10 at the same bit-rate requires setting the "Quality" slider to 4 out of 100, i.e. almost at the low end of the quality scale.

Anyway, I can confirm that the current rate control algorithm greatly underestimates the bit-rate requirements on some low-rate encoded still images. For the performance of the current VVenC development version towards release 1.2, see the attached picture, top right (QP 50, 2.5 kbytes). The bottom row shows you an estimate (one of two possible variants) of how VVenC 1.2 will perform (QP 45, roughly 9.5 kbytes) with the following two changes:

1. a modification of the rate control algorithm for still image coding, which we will publish here on GitHub as soon as possible,
2. running the encoder twice. With the modifications from 1., the resulting bit-rate increases from 2.5 to roughly 7.1-7.4 kbytes, which is still a bit off due to the fact that the rate control is primarily intended for video coding. However, you can run VVenC a second time in 2-pass rate control mode, with the `-b 80000` changed to 80000 * 80000/(8 * *byte-size of first encoding result*), i.e., `-b 108108` for a first output size of 7.4 kbytes. That seems to result in quite accurate rate matching with the modified rate control algorithm in my own experiments (it does not, however, seem to work as well with the existing VVenC 1.1 behavior).

![image_840x628_issue93](https://user-images.githubusercontent.com/71433742/133294670-2101d0c6-5d81-4b2c-8153-9a6b5ba3b4ae.jpg)

I'll notify you here once the relevant update to the VVenC source code has been made available.

Christian

**Comment by rafael2k** [comment]
The mentioned improvements you are writing are wonderful Chris. I'll re-run my tests as soon as you commit them. Cheers!

**Comment by rafael2k** [comment]
Wonderful! One question: how to use the two-pass mode with statistics file? 
It is just a matter of setting passes 1 and 2 and set the same statistics file to the same path, correct?

**Comment by rafael2k** [comment]
Hi Adam. I'm trying the new version, and it gives me way out results, like 8 times more the desired bitrate after the second pass. Is there any caveat in the bitrate setting?

**Comment by rafael2k** [comment]
Setting "-f 1", I get even worse results (but at least a correct frame count in the output), with the output bitrate 10x less in some images after the second pass.

**Comment by adamjw24** [comment]
Reopening, since some outstanding issues still exist

**Comment by adamjw24** [comment]
Great, looking forward to the results.

As for now, we'd appreciate any additional info you could give us (problematic source images, exact commands etc.).

**Comment by rafael2k** [comment]
With some inputs I still get a 30%+ error to the rate set. I put my small target material here:
http://164.41.155.66/rafael/hermes_picture_tests/images/
