### ISSUE TITLE
Unable to build on Windows

### ISSUE THREAD

**Issue by yotoprules** [fraunhoferhhi/vvenc#94]
Hi,
Whenever I try to build, I always get "error 1" and the only thing in the CMakeOutput.log is `The system is: Windows - 10.0.19043 - AMD64`.
I'm using cmake 2.21.2, make 3.81, and visual studio 2019.

Using a command prompt running as admin: `make install-release` I get this output:

`cmake --build build/static --config Release  -- /maxcpucount:20 /verbosity:minimal /nr:false
CMake Error:
  Generator

    NMake Makefiles

  does not support platform specification, but platform

    x64

  was specified.

make: *** [release] Error 1`

It's probably something simple I'm missing...

**Comment by adamjw24** [comment]
Hi, good catch. This is a mistake on our side, we should be checking the generator and not the OS. For now, you can workaround this issue by commenting out the following lines:
https://github.com/fraunhoferhhi/vvenc/blob/0e6ca4febb21facec606fe803273fed31beec6fc/Makefile#L70-L71

Alternatively, you could create the project using CMake directly, and skipping the faulty Makefile for now.

You might run into some other issue there, tho. Make sure you have an appropriate compiler. If CMake doesn't recognize it, set CC and CXX environment variables appropriately.

We will have a look and try to upload a fix soon.

**Comment by adamjw24** [comment]
Could you describe your environment?

We talked about this a bit and it seems there are a lot of different options, way too many to support.

**Comment by adamjw24** [comment]
Sorry, I misread your message. You want to build using Visual Studio.

You mistyped your CMake version, right? The 2.21 is really old by now, and the project requires at least 3.13.

Best regards,
Adam

**Comment by blueskyfor** [comment]
Hi, 
I had the same problem, so I commented lines 70 and 71 and then repeated command make install-release.
After that I got another error

cmake --build build/release-static  -- /maxcpucount:4 /verbosity:minimal /nr:fal
se
Не удается найти указанный файл
CMake Error: Generator: execution of make failed. Make command was: nmake -f Mak
efile /nologo /maxcpucount:4 /verbosity:minimal /nr:false &&
make: *** [release] Error 1

**Comment by blueskyfor** [comment]
> Sorry, I misread your message. You want to build using Visual Studio.
> 
> You mistyped your CMake version, right? The 2.21 is really old by now, and the project requires at least 3.13.
> 
> Best regards,
> Adam

Hi,
I had the same problem, so I commented lines 70 and 71 and then repeated command make install-release.
After that I got another error

cmake --build build/release-static -- /maxcpucount:4 /verbosity:minimal /nr:fal
se
Не удается найти указанный файл
CMake Error: Generator: execution of make failed. Make command was: nmake -f Mak
efile /nologo /maxcpucount:4 /verbosity:minimal /nr:false &&
make: *** [release] Error 1

**Comment by adamjw24** [comment]
Hey. So it seems in the console CMake does not recognize your Visual Studio installation, otherwise it would choose it as its default generator. The makefile is only a simple wrapper around the actual CMake build system, that vvenc is based on. Could you maybe open the project in CMake GUI and see if the Visual Studio generator is available?

Best regards,
Adam

**Comment by blueskyfor** [comment]
> Hey. So it seems in the console CMake does not recognize your Visual Studio installation, otherwise it would choose it as its default generator. The makefile is only a simple wrapper around the actual CMake build system, that vvenc is based on. Could you maybe open the project in CMake GUI and see if the Visual Studio generator is available?
> 
> Best regards,
> Adam

Okay, I don't know if i did everything right, but here's what i got. Sorry, i just use all these programms for the first time in my life and don't have a good understanding on what i'm doing
![0UIolEaeAec](https://user-images.githubusercontent.com/90324222/132510033-10836652-fe55-4c8d-94d8-0ec7ba46e340.jpg)

**Comment by adamjw24** [comment]
Thats alright. You have to point the source code (first line) to where you checked out the source. The "Where to build the binaries" should point to a "build" directory within the source directory. Otherwise you could just open the project in Visual Studio. VS 16 2019 can open a directory containing CMakeLists.txt file just like that (if all parts are installed properly). Than you just have to select the release configuration and run the build. Sorry I don't have an easier solution.

**Comment by blueskyfor** [comment]
> Thats alright. You have to point the source code (first line) to where you checked out the source. The "Where to build the binaries" should point to a "build" directory within the source directory. Otherwise you could just open the project in Visual Studio. VS 16 2019 can open a directory containing CMakeLists.txt file just like that (if all parts are installed properly). Than you just have to select the release configuration and run the build. Sorry I don't have an easier solution.

So, i did this (opened in VS file CMakeLists.txt). Is it right? And if it's right, what do i do next? Just press the button i underlined in red
![Безымянный](https://user-images.githubusercontent.com/90324222/132512526-a4a1d95e-6f47-4969-b284-66c5e456b3d9.jpg)
![Безымянный1](https://user-images.githubusercontent.com/90324222/132512536-159b1258-3a58-4f32-b4c3-319e05e12085.jpg)

**Comment by adamjw24** [comment]
So the way it worked for me is.

1. Open Visual Studio.
2. Open Folder and navigate to the directory. (this is I think what you did)

3. On the top, right of "x64-Release" (used to be x64-Debug before step 4) push the Dropdown menu and select "Manage Configurations"
![image](https://user-images.githubusercontent.com/70575289/132513426-adc2c458-034a-4db8-bef2-1ae17b6d5999.png)
4. Change the configuration name to x64-Release and "Configuration type" to "Release" and save.
![image](https://user-images.githubusercontent.com/70575289/132513758-ef863b3c-557d-4f40-828e-eaec195e23c9.png)
5. In the top menu, navigate to "Build" menu and select "Build all"
![image](https://user-images.githubusercontent.com/70575289/132514274-3e25eadd-01ca-42d9-bbd7-87a86f529f96.png)

You would need to figure out how the steps are called in Russian (?).

**Comment by blueskyfor** [comment]
> So the way it worked for me is.
> 
> 1. Open Visual Studio.
> 2. Open Folder and navigate to the directory. (this is I think what you did)
> 3. On the top, right of "x64-Release" (used to be x64-Debug before step 4) push the Dropdown menu and select "Manage Configurations"
>    ![image](https://user-images.githubusercontent.com/70575289/132513426-adc2c458-034a-4db8-bef2-1ae17b6d5999.png)
> 4. Change the configuration name to x64-Release and "Configuration type" to "Release" and save.
>    ![image](https://user-images.githubusercontent.com/70575289/132513758-ef863b3c-557d-4f40-828e-eaec195e23c9.png)
> 5. In the top menu, navigate to "Build" menu and select "Build all"
>    ![image](https://user-images.githubusercontent.com/70575289/132514274-3e25eadd-01ca-42d9-bbd7-87a86f529f96.png)
> 
> You would need to figure out how the steps are called in Russian (?).

It's me again. I have some problems. So, let me explain what i've done step by step.

1. I opened VS and chose "open folder"
![1](https://user-images.githubusercontent.com/90324222/132568863-c511c05a-c387-4749-b37a-da0e20b41ded.jpg)

2. Then I opened this folder, which contains all the files I downloaded from the web-site
![2](https://user-images.githubusercontent.com/90324222/132569063-2127c134-9a98-45e9-8439-e6a176085e46.jpg)

3. After that my VS started to look like this
![3](https://user-images.githubusercontent.com/90324222/132569172-6959c648-3d16-4f1b-8673-db1f05bce9c2.jpg)

As you can see, I changed the configuration name to x64-Release

4. And the problem is should I open some specific file among all these files which I downloaded and what do I do if my Build menu looks like this?
![4](https://user-images.githubusercontent.com/90324222/132569488-53a735e5-de14-418b-a260-0b391b493350.jpg)

In previous answers you wrote that I have to open a directory containing CMakeLists.txt and then have to select the release configuration. But, cn you, please, tell me, what's the name of this file which contains release configuration?

**Comment by adamjw24** [comment]
Thats strange. If seems you did everything right (but please make sure you not only changed the name to x64-Release, but also changed the configuration to "Release" - see my picture again). The build dropdown *should* show the build option.

Are you sure you Visual Studio installation is correct and contains all of the C++ related components? To me it seems like something is missing, which would explain why CMake doesn't per default choose visual studio as builder.

In the visual studio installer, please make sure to select all points under both "Desktop development with C++" and "Linux Development with C++"
